services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - stackly_network
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - stackly_network
    environment:
      NODE_ENV: production
    volumes:
      - sqlite_data:/data
networks:
  stackly_network:
    external: true

volumes:
  sqlite_data:
